"use client"

import "./globals.css";

import {AntdRegistry} from "@ant-design/nextjs-registry";
import {AuthProvider} from "@/contexts/AuthContext";
import '@ant-design/v5-patch-for-react-19';


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" className="h-screen">
        <body className="h-screen">
        <AuthProvider>
            <AntdRegistry>
                {children}
            </AntdRegistry>
        </AuthProvider>
        </body>
        </html>
    );
}
